language: cpp
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get update -qq
    - sudo apt-get -qq install libboost-test-dev libsdl-image1.2-dev libsdl-ttf2.0-dev
script: mkdir build && cd build && cmake ../ && make && ctest
